Repository tinylunark/lunark-back, pull requests merged in 2023-12, with the labels that each got.

#26 Amenities
  src/main/java/com/lunark/lunark/amenities/controller/AmenityController.java
  src/main/java/com/lunark/lunark/amenities/dto/AmenityRequestDto.java
  src/main/java/com/lunark/lunark/amenities/dto/AmenityResponseDto.java
  src/main/java/com/lunark/lunark/amenities/model/Amenity.java
  src/main/java/com/lunark/lunark/amenities/repository/IAmenityRepository.java
  src/main/java/com/lunark/lunark/amenities/service/AmenityService.java
  src/main/java/com/lunark/lunark/amenities/service/IAmenityService.java
  src/main/java/com/lunark/lunark/properties/controller/AmenityController.java
  src/main/java/com/lunark/lunark/properties/controller/PropertyController.java
  src/main/java/com/lunark/lunark/properties/dto/PropertyRequestDto.java
  src/main/java/com/lunark/lunark/properties/dto/PropertyResponseDto.java
  src/main/java/com/lunark/lunark/properties/model/Property.java
  src/test/java/com/lunark/lunark/property/model/PropertyTests.java
  src/test/java/com/lunark/lunark/property/service/PropertyServiceTests.java
Labels: feature

#25 #3.1.2 Property Search and Filters
  src/main/java/com/lunark/lunark/mapper/PropertyDtoMapper.java
  src/main/java/com/lunark/lunark/properties/controller/PropertyController.java
  src/main/java/com/lunark/lunark/properties/dto/AvailabilityEntryDto.java
  src/main/java/com/lunark/lunark/properties/dto/PropertyRequestDto.java
  src/main/java/com/lunark/lunark/properties/dto/PropertyResponseDto.java
  src/main/java/com/lunark/lunark/properties/dto/PropertySearchDto.java
  src/main/java/com/lunark/lunark/properties/model/Property.java
  src/main/java/com/lunark/lunark/properties/repostiory/IPropertyRepository.java
  src/main/java/com/lunark/lunark/properties/service/IPropertyService.java
  src/main/java/com/lunark/lunark/properties/service/PropertyService.java
  src/main/java/com/lunark/lunark/properties/specification/PropertySpecification.java
  src/test/java/com/lunark/lunark/property/model/PropertyTests.java
  src/test/java/com/lunark/lunark/property/service/PropertyServiceTests.java
Labels: feature

#28 Enable connection with frontend after adding security
  src/main/java/com/lunark/lunark/auth/model/Account.java
  src/main/java/com/lunark/lunark/security/AuthRequest.java
  src/main/java/com/lunark/lunark/security/AuthenticationController.java
  src/main/java/com/lunark/lunark/security/WebSecurityConfiguration.java
  src/main/java/com/lunark/lunark/util/TokenUtils.java
  src/main/resources/import.sql
Labels: fix

#30 Fix: Add cors header in 401 response
  src/main/java/com/lunark/lunark/security/TokenEntryPoint.java
Labels: fix

#35 Don't set password to null in database if it wasn't changed and hash changed passwords
  src/main/java/com/lunark/lunark/auth/controller/AccountController.java
  src/main/java/com/lunark/lunark/auth/service/AccountService.java
Labels: fix

#37 Do not return unapproved properties when getting all properties
  src/main/java/com/lunark/lunark/properties/specification/PropertySpecification.java
Labels: fix

#38 Feature/9.6/booking reservation request
  src/main/java/com/lunark/lunark/auth/model/Account.java
  src/main/java/com/lunark/lunark/properties/model/Property.java
  src/main/java/com/lunark/lunark/reservations/controller/ReservationController.java
  src/main/java/com/lunark/lunark/reservations/dto/ReservationConfirmationDto.java
  src/main/java/com/lunark/lunark/reservations/dto/ReservationRequestDTO.java
  src/main/java/com/lunark/lunark/reservations/dto/ReservationRequestDto.java
  src/main/java/com/lunark/lunark/reservations/dto/ReservationResponseDto.java
  src/main/java/com/lunark/lunark/reservations/model/Reservation.java
  src/main/java/com/lunark/lunark/reservations/repository/IReservationRepository.java
  src/main/java/com/lunark/lunark/reservations/service/IReservationService.java
  src/main/java/com/lunark/lunark/reservations/service/ReservationService.java
  src/test/java/com/lunark/lunark/reservation/service/ReservationServiceTests.java
Labels: feature

#43 Soft delete all top level entities
  src/main/java/com/lunark/lunark/amenities/model/Amenity.java
  src/main/java/com/lunark/lunark/auth/model/Account.java
  src/main/java/com/lunark/lunark/auth/model/VerificationLink.java
  src/main/java/com/lunark/lunark/properties/model/Property.java
  src/main/java/com/lunark/lunark/reservations/model/Reservation.java
  src/main/java/com/lunark/lunark/reviews/model/Review.java
Labels: enhancement

#46 feat: add pre auth to properties controller
  src/main/java/com/lunark/lunark/properties/controller/PropertyController.java
Labels: feature

#50 Feature/2.9/favorite properties
  src/main/java/com/lunark/lunark/auth/controller/AccountController.java
  src/main/java/com/lunark/lunark/auth/model/Account.java
  src/main/java/com/lunark/lunark/auth/service/AccountService.java
  src/main/java/com/lunark/lunark/auth/service/IAccountService.java
Labels: feature

#52 Favorite property deletion
  src/main/java/com/lunark/lunark/auth/controller/AccountController.java
  src/main/java/com/lunark/lunark/auth/service/AccountService.java
  src/main/java/com/lunark/lunark/auth/service/IAccountService.java
Labels: enhancement

#51 Fix the binding of hosts and amenities to properties
  src/main/java/com/lunark/lunark/mapper/PropertyDtoMapper.java
  src/main/java/com/lunark/lunark/properties/controller/PropertyController.java
  src/main/java/com/lunark/lunark/properties/dto/PropertyRequestDto.java
Labels: bug

#54 feat: add latitude and longitude fields to property request dto
  src/main/java/com/lunark/lunark/properties/dto/PropertyRequestDto.java
Labels: enhancement

#57 Profile image upload and retrieval
  src/main/java/com/lunark/lunark/auth/controller/AccountController.java
  src/main/java/com/lunark/lunark/auth/dto/AccountDto.java
  src/main/java/com/lunark/lunark/auth/model/Account.java
  src/main/java/com/lunark/lunark/auth/model/ProfileImage.java
  src/main/java/com/lunark/lunark/auth/service/AccountService.java
  src/main/java/com/lunark/lunark/auth/service/IAccountService.java
Labels: enhancement
