Repository tinylunark/lunark-back, pull requests merged in 2023-11, with the labels that each got.

#5 Properties
  src/main/java/com/lunark/lunark/controller/PropertyController.java
  src/main/java/com/lunark/lunark/dto/PropertyDto.java
  src/main/java/com/lunark/lunark/model/Address.java
  src/main/java/com/lunark/lunark/model/PricingMode.java
  src/main/java/com/lunark/lunark/model/Property.java
  src/main/java/com/lunark/lunark/service/PropertyService.java
  src/main/java/com/lunark/lunark/service/PropertyServiceImpl.java
Labels: feature

#6 Notifications API
  src/main/java/com/lunark/lunark/controller/NotificationController.java
  src/main/java/com/lunark/lunark/dto/NotificationDto.java
  src/main/java/com/lunark/lunark/model/Notification.java
Labels: feature

#11 Property and notification DTOs
  pom.xml
  src/main/java/com/lunark/lunark/controller/NotificationController.java
  src/main/java/com/lunark/lunark/controller/PropertyController.java
  src/main/java/com/lunark/lunark/dto/NotificationDto.java
  src/main/java/com/lunark/lunark/dto/NotificationResponseDto.java
  src/main/java/com/lunark/lunark/dto/PropertyDto.java
  src/main/java/com/lunark/lunark/dto/PropertyRequestDto.java
  src/main/java/com/lunark/lunark/dto/PropertyResponseDto.java
Labels: refactor

#15 Update: Average Grade Endpoints
  src/main/java/com/lunark/lunark/controller/AccountController.java
  src/main/java/com/lunark/lunark/controller/PropertyController.java
  src/main/java/com/lunark/lunark/service/AccountService.java
  src/main/java/com/lunark/lunark/service/AccountServiceImpl.java
  src/main/java/com/lunark/lunark/service/PropertyService.java
  src/main/java/com/lunark/lunark/service/PropertyServiceImpl.java
Labels: enhancement

#17 Fine grained notification settings
  src/main/java/com/lunark/lunark/controller/NotificationSettingsController.java
  src/main/java/com/lunark/lunark/dto/AccountDto.java
  src/main/java/com/lunark/lunark/dto/GuestNotificationSettingsDto.java
  src/main/java/com/lunark/lunark/dto/HostNotificationSettingsDto.java
  src/main/java/com/lunark/lunark/model/Account.java
  src/main/java/com/lunark/lunark/model/GuestNotificationSettings.java
  src/main/java/com/lunark/lunark/model/HostNotificationSettings.java
Labels: feature

#16 Review approval endpoint
  src/main/java/com/lunark/lunark/controller/ReviewApprovalController.java
  src/main/java/com/lunark/lunark/controller/ReviewController.java
  src/main/java/com/lunark/lunark/dto/ReviewApprovalDto.java
  src/main/java/com/lunark/lunark/repository/ReviewRepository.java
Labels: feature

#19 Favorite Endpoint
  src/main/java/com/lunark/lunark/controller/AccountController.java
  src/main/java/com/lunark/lunark/dto/AccountDto.java
  src/main/java/com/lunark/lunark/model/Account.java
  src/main/java/com/lunark/lunark/service/AccountService.java
  src/main/java/com/lunark/lunark/service/AccountServiceImpl.java
Labels: enhancement, feature

#18 feat: Record endpoints
  src/main/java/com/lunark/lunark/controller/PropertyReportController.java
  src/main/java/com/lunark/lunark/dto/PropertyReportDto.java
Labels: enhancement, feature

#14 API endpoints
  src/main/java/com/lunark/lunark/controller/AccountController.java
  src/main/java/com/lunark/lunark/controller/PropertyController.java
  src/main/java/com/lunark/lunark/model/Property.java
Labels: feature
