Repository tinylunark/lunark-back, pull requests merged in 2024-01, with the labels that each got.

#63 Property average rating
  src/main/java/com/lunark/lunark/properties/dto/PropertyResponseDto.java
  src/main/java/com/lunark/lunark/properties/model/Property.java
Labels: feature

#70 Fix availability entries not being saved when editing property
  src/main/java/com/lunark/lunark/properties/model/Property.java
Labels: fix

#66 Host review notifications 7.5
  src/main/java/com/lunark/lunark/auth/model/Account.java
  src/main/java/com/lunark/lunark/notifications/service/INotificationService.java
  src/main/java/com/lunark/lunark/notifications/service/NotificationService.java
  src/main/java/com/lunark/lunark/properties/model/Property.java
  src/main/java/com/lunark/lunark/reviews/controller/ReviewController.java
  src/main/java/com/lunark/lunark/reviews/model/Review.java
  src/main/java/com/lunark/lunark/reviews/service/IReviewService.java
  src/main/java/com/lunark/lunark/reviews/service/ReviewService.java
Labels: feature

#67 Review reporting 8.7
  src/main/java/com/lunark/lunark/mapper/ReviewReportDtoMapper.java
  src/main/java/com/lunark/lunark/moderation/controller/ReviewReportController.java
  src/main/java/com/lunark/lunark/moderation/dto/ReviewReportResponseDto.java
  src/main/java/com/lunark/lunark/moderation/exception/UnauthorizedReportException.java
  src/main/java/com/lunark/lunark/moderation/model/ReviewReport.java
  src/main/java/com/lunark/lunark/moderation/service/IReviewReportService.java
  src/main/java/com/lunark/lunark/moderation/service/ReviewReportService.java
  src/main/resources/import.sql
Labels: feature

#68 Feature/9.3/search and filter requests
  src/main/java/com/lunark/lunark/auth/dto/AccountDto.java
  src/main/java/com/lunark/lunark/auth/model/Account.java
  src/main/java/com/lunark/lunark/reservations/controller/ReservationController.java
  src/main/java/com/lunark/lunark/reservations/dto/ReservationResponseDto.java
  src/main/java/com/lunark/lunark/reservations/dto/ReservationSearchDto.java
  src/main/java/com/lunark/lunark/reservations/repository/IReservationRepository.java
  src/main/java/com/lunark/lunark/reservations/service/IReservationService.java
  src/main/java/com/lunark/lunark/reservations/service/ReservationService.java
  src/main/java/com/lunark/lunark/reservations/specification/ReservationSpecification.java
Labels: feature

#74 Host average rating
  src/main/java/com/lunark/lunark/auth/dto/AccountDto.java
  src/main/java/com/lunark/lunark/auth/model/Account.java
Labels: feature

#78 Fix ids of filtered reservations being `undefined` on the frontend
  src/main/java/com/lunark/lunark/reservations/dto/ReservationResponseDto.java
Labels: fix

#73 Guests can report hosts 8.4
  src/main/java/com/lunark/lunark/mapper/AccountReportDtoMapper.java
  src/main/java/com/lunark/lunark/moderation/controller/AccountReportController.java
  src/main/java/com/lunark/lunark/moderation/dto/AccountReportRequestDto.java
  src/main/java/com/lunark/lunark/moderation/dto/AccountReportResponseDto.java
  src/main/java/com/lunark/lunark/moderation/dto/HostReportEligibilityDto.java
  src/main/java/com/lunark/lunark/moderation/model/AccountReport.java
  src/main/java/com/lunark/lunark/moderation/repository/IAccountReportRepository.java
  src/main/java/com/lunark/lunark/moderation/service/AccountReportService.java
  src/main/java/com/lunark/lunark/moderation/service/IAccountReportService.java
  src/main/resources/import.sql
Labels: feature

#75 Hosts can report guests 8.3
  src/main/java/com/lunark/lunark/moderation/controller/AccountReportController.java
  src/main/java/com/lunark/lunark/moderation/service/AccountReportService.java
Labels: feature

#79 Story #9.6 - Booking request deletion
  src/main/java/com/lunark/lunark/reservations/controller/ReservationController.java
  src/main/java/com/lunark/lunark/reservations/service/IReservationService.java
  src/main/java/com/lunark/lunark/reservations/service/ReservationService.java
Labels: feature

#80 Story #7.2 - Notifications toggle
  src/main/java/com/lunark/lunark/auth/controller/AccountController.java
  src/main/java/com/lunark/lunark/auth/dto/AccountDto.java
  src/main/java/com/lunark/lunark/auth/model/Account.java
  src/main/java/com/lunark/lunark/auth/service/AccountService.java
  src/main/java/com/lunark/lunark/auth/service/IAccountService.java
  src/main/java/com/lunark/lunark/notifications/dto/NotificationSettingsDto.java
  src/main/java/com/lunark/lunark/notifications/model/GuestNotificationSettings.java
  src/main/java/com/lunark/lunark/notifications/model/HostNotificationSettings.java
  src/main/java/com/lunark/lunark/notifications/service/NotificationService.java
Labels: feature

#82 Story #7.3 - Reservation request notification
  src/main/java/com/lunark/lunark/notifications/service/NotificationService.java
  src/main/java/com/lunark/lunark/reservations/service/ReservationService.java
Labels: feature

#83 Fix failing tests
  src/test/java/com/lunark/lunark/configuration/TestConfiguration.java
  src/test/java/com/lunark/lunark/property/controller/PropertyControllerPricesAndAvailabilityIntegrationTests.java
  src/test/java/com/lunark/lunark/reservations/repository/ReservationRepositoryTest.java
  src/test/resources/past-reservation-test-data.sql
Labels: fix

#84 Story #2.8 - Reports
  src/main/java/com/lunark/lunark/reports/controller/ReportController.java
  src/main/java/com/lunark/lunark/reports/dto/GeneralReportResponseDto.java
  src/main/java/com/lunark/lunark/reports/dto/PropertyReportRequestDto.java
  src/main/java/com/lunark/lunark/reports/dto/PropertyReportResponseDto.java
  src/main/java/com/lunark/lunark/reports/model/GeneralReport.java
  src/main/java/com/lunark/lunark/reports/model/MonthlyReport.java
  src/main/java/com/lunark/lunark/reports/service/IReportService.java
  src/main/java/com/lunark/lunark/reports/service/ReportService.java
  src/main/java/com/lunark/lunark/reservations/repository/IReservationRepository.java
  src/test/java/com/lunark/lunark/reservation/service/ReservationServiceTests.java
Labels: feature

#85 Add host report validations 8.4.2
  src/main/java/com/lunark/lunark/errorhandling/ErrorMessage.java
  src/main/java/com/lunark/lunark/errorhandling/RestExceptionHandler.java
  src/main/java/com/lunark/lunark/exceptions/AccountNotFoundException.java
  src/main/java/com/lunark/lunark/mapper/AccountReportDtoMapper.java
  src/main/java/com/lunark/lunark/moderation/controller/AccountReportController.java
  src/main/java/com/lunark/lunark/moderation/dto/AccountReportRequestDto.java
  src/main/java/com/lunark/lunark/moderation/service/AccountReportService.java
  src/main/java/com/lunark/lunark/validation/AccountExistsConstraint.java
  src/main/java/com/lunark/lunark/validation/AccountExistsConstraintValidator.java
  src/main/java/com/lunark/lunark/validation/HostExistsConstraint.java
  src/main/java/com/lunark/lunark/validation/HostExistsConstraintValidator.java
Labels: fix

#87 Add validations to login
  src/main/java/com/lunark/lunark/security/AuthRequest.java
  src/main/java/com/lunark/lunark/security/AuthenticationController.java
Labels: fix

#89 Add validations to `PropertyController`
  src/main/java/com/lunark/lunark/errorhandling/RestExceptionHandler.java
  src/main/java/com/lunark/lunark/mapper/PropertyDtoMapper.java
  src/main/java/com/lunark/lunark/properties/controller/PropertyController.java
  src/main/java/com/lunark/lunark/properties/dto/AvailabilityEntryDto.java
  src/main/java/com/lunark/lunark/properties/dto/PropertyRequestDto.java
  src/main/java/com/lunark/lunark/properties/model/Address.java
  src/main/java/com/lunark/lunark/properties/model/Property.java
  src/main/java/com/lunark/lunark/validation/AmenitiesExistConstraint.java
  src/main/java/com/lunark/lunark/validation/AmenitiesExistsConstraintValidator.java
  src/main/java/com/lunark/lunark/validation/ValidMinMaxGuests.java
  src/main/java/com/lunark/lunark/validation/ValidMinMaxGuestsValidator.java
  src/main/java/com/lunark/lunark/validation/ValidPropertySearchDates.java
  src/main/java/com/lunark/lunark/validation/ValidPropertySearchDatesValidator.java
  src/main/java/com/lunark/lunark/validation/ValidPropertySearchPrices.java
  src/main/java/com/lunark/lunark/validation/ValidPropertySearchPricesValidator.java
  src/main/resources/import.sql
  src/test/java/com/lunark/lunark/property/service/PropertyServiceTests.java
  src/test/resources/test-data-availability.sql
Labels: fix

#90 Add validations for reviews
  src/main/java/com/lunark/lunark/reviews/controller/ReviewController.java
  src/main/java/com/lunark/lunark/reviews/dto/ReviewRequestDto.java
Labels: fix

#94 Reservation creation integration and unit tests
  src/test/java/com/lunark/lunark/reservation/controller/ReservationControllerIntegrationTests.java
  src/test/java/com/lunark/lunark/reservation/service/ReservationServiceTests.java
  src/test/resources/reservation-creation-test-data.sql
Labels: test

#95 Property search sort order
  src/main/java/com/lunark/lunark/properties/controller/PropertyController.java
  src/main/java/com/lunark/lunark/properties/dto/PropertySearchDto.java
  src/main/java/com/lunark/lunark/properties/specification/PropertySpecification.java
Labels: enhancement

#97 Property availability integration tests
  src/main/java/com/lunark/lunark/auth/controller/AccountController.java
  src/main/java/com/lunark/lunark/auth/service/AccountService.java
  src/main/java/com/lunark/lunark/mapper/PropertyDtoMapper.java
  src/main/java/com/lunark/lunark/properties/controller/PropertyController.java
  src/main/java/com/lunark/lunark/properties/model/Address.java
  src/main/java/com/lunark/lunark/properties/service/PropertyService.java
  src/main/java/com/lunark/lunark/reservations/repository/IReservationRepository.java
  src/main/java/com/lunark/lunark/reservations/service/IReservationService.java
  src/main/java/com/lunark/lunark/reservations/service/ReservationService.java
  src/test/java/com/lunark/lunark/configuration/TestConfiguration.java
  src/test/java/com/lunark/lunark/property/controller/PropertyControllerPricesAndAvailabilityIntegrationTests.java
  src/test/java/com/lunark/lunark/property/repostiory/PropertyRepositoryTests.java
  src/test/java/com/lunark/lunark/property/service/PropertyServiceTests.java
  src/test/java/com/lunark/lunark/reservation/service/ReservationServiceTests.java
  src/test/java/com/lunark/lunark/reservations/repository/ReservationRepositoryTest.java
  src/test/resources/find-reservations-containing-date-test-data.sql
  src/test/resources/test-data-availability.sql
Labels: test

#99 Write README
  README.md
Labels: documentation

#96 E2E testing setup
  .gitignore
  pom.xml
  src/test/java/com/lunark/lunark/e2e/TestBase.java
Labels: test

#102 Allow apostrophes and quotes in longer text fields
  src/main/java/com/lunark/lunark/moderation/dto/AccountReportRequestDto.java
  src/main/java/com/lunark/lunark/properties/dto/PropertyRequestDto.java
  src/main/java/com/lunark/lunark/reviews/dto/ReviewRequestDto.java
Labels: fix
